<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
 <TargetFrameworks>net10.0-windows;net9.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuExt.Minimal.Mvvm" Version="0.7.3" />
    <PackageReference Include="NuExt.Minimal.Mvvm.SourceGenerator" Version="0.7.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NuExt.Minimal.Behaviors.Wpf.csproj" />
  </ItemGroup>

</Project>
